
spring:
  datasource:
    password: yourpassword
    url: jdbc:mysql://localhost:3306/serverdb
    username: yourusername
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true